### ISSUE TITLE
TypeError: May not write null values to stream

### ISSUE THREAD

**Issue by franck34** [drob/s3-deleter#1]
Running node 6.9.4 on Debian.

Trying to delete S3 item return an error:

```
TypeError: May not write null values to stream
at validChunk (_stream_writable.js:211:10)
at S3Deleter.Writable.write (_stream_writable.js:245:12)
at S3Deleter.module.exports.S3Deleter.end (/var/www/xxxxx.com/dev/node_modules/s3-deleter/lib/index.js:66:19)
at S3Lister.onend (/var/www/xxxxx.com/dev/node_modules/s3-lister/node_modules/readable-stream/lib/_stream_readable.js:523:10)
at S3Lister.g (events.js:291:16)
at emitNone (events.js:86:13)
at S3Lister.emit (events.js:185:7)
at /var/www/xxxxx.com/dev/node_modules/s3-lister/node_modules/readable-stream/lib/_stream_readable.js:965:16
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Any idea ? 

thank you !

**Comment by drob** [comment]
Thanks for the issue report!

Do you have a code excerpt that reproduces this issue? I tried reproducing it myself without success.

**Comment by drob** [comment]
Ah, found a repro. Are you calling `deleter.end(null)` by chance?

**Comment by franck34** [comment]
Hi ! thanks for your reactivity !

Below my code

```
var s3Options = {
    key: 'xxxx',
    secret: 'xxxxxxxx',
    bucket: 'xxxxxx-s3'
};

var knoxClient = knox.createClient(s3Options);

var listerDev = new S3Lister(knoxClient,{prefix:'dev/12345'});
var deleterDev = new S3Deleter(knoxClient);

deleterDev.on('error',function (err) {
    console.log('on error','deleterDev', err);
});

listerDev.on('error',function(err) {
    console.log('on error','listerDev', err);
});

try {
    listerDev.pipe(deleterDev);
} catch(e) {
    console.log('try catch error',e.message);
}
```

**Comment by drob** [comment]
Would you mind adding an `.on('data', ...)` listener to `listerDev`? I am curious what is being passed to `deleterDev`. I believe it's something null at some point.

Alternately, if this is test data and you're comfortable doing so, you could send me the credentials to that bucket and I can reproduce and investigate on my own.

**Comment by franck34** [comment]
Yep, it's for test. Let me send you an email.

**Comment by franck34** [comment]
Hi

I tried to debug myself, but no time/enought knowledge.

Switching back to old school extension for knox client.

https://gist.github.com/franck34/b1ab4c7ecf27023a2f68320ba6a3fd0a
